export const {
  VITE_APP_KEYCLOAK_ENABLED,
  VITE_APP_KEYCLOAK_JS_URL,
  VITE_APP_KEYCLOAK_JS_REALM,
  VITE_APP_KEYCLOAK_JS_CLIENT_ID,
  VITE_APP_REFRESH_TOKEN_MS,
  VITE_APP_BACKEND_DEV_URL,
  VITE_APP_BACKEND_PROD_URL,
  VITE_PATH_BUILD,
  DEV: IsDevMode,
} = import.meta.env;
